### ISSUE TITLE
add testing framework to adjust state and works with hooks

### ISSUE THREAD

**Issue by KevinDanikowski** [amclin/react-project-boilerplate#149]
It was found that react-test-renderer is limited in its functionality in changing state to test further functionality. As a result the two best options were enzyme and react-testing-library which facebook supports. 

After a team discussion, it was decided to do a POC with react-testing-library, support for this decision can be found here: https://medium.com/@boyney123/my-experience-moving-from-enzyme-to-react-testing-library-5ac65d992ce

**Comment by amclin** [comment]
Currently the only testing framework (on top of jest) is `react-test-renderer`. `enzyme` is specifically not used because it still can't handle React hooks:
https://github.com/airbnb/enzyme/issues/2011 

`react-testing-library` seems to be a suitable alternative. Regardless of solution chosen, I'd prefer to see only one such framework in use. It gets very confusing for developers when multiple frameworks are mixed, as they often have different testing patterns and requirements for bootstrapping for test cases - especially for asynchronous tests.

**Comment by amclin** [comment]
Fixed by #179
