### ISSUE TITLE
add example using context state management

### ISSUE THREAD

**Issue by KevinDanikowski** [amclin/react-project-boilerplate#192]
apps may need to use state management at some point. we should provide an example of how to implement such a solution, or link to the code to implement a solution.

**Comment by amclin** [comment]
Although it is a common pattern in the React world, state management really shouldn't be at the global context level since it leads to misuse.

Instead, it's best to keep state local to the components that need it (state colocation). Here's a great article explaining it, and showing patterns for avoiding global state management:
https://kentcdodds.com/blog/state-colocation-will-make-your-react-app-faster
